spring:
  application:
    name: simpletodo
  data:
    mongodb:
      port: 27017
  security:
    oauth2:
      client:
        registration:
          google: # CommonOAuth2Provider Enum 필요한 엔드포인트들이 제공되어 있음.
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

server:
  port: 8080