spring:
  application:
    name: simpletodo
  data:
    mongodb:
      port: 27017
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

server:
  port: 8080